services:
  - type: web
    name: blog-database
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 5 